services:
  qc.fair_woolly-cerise-tamarin:
    image: steinsteiny/fuji:v1.3.8.full
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
